name: trip_app_ui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Ensures material design icons are included.
  uses-material-design: true

  # Declare assets used by the app.
  assets:
    - assets/images/one.jpg
    - assets/images/two.jpg
    - assets/images/three.jpg
    - assets/images/four.jpg
  #    - images/a_dot_ham.jpeg

  # Uncomment and configure fonts if needed:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
