/* Land Readjustment Platform — translation dictionary (EN fallback). RW/FR are drafts pending NLA review. */
(function(){
const EN={story:'Story',map:'Map',analytics:'Analytics',about:'About',overview:'National overview',find:'Find my land',ph:'Enter your UPI, e.g. 4/01/09/04/106',search:'Search',signin:'Sign in',dm:'Data manager',
allSites:'all sites',hint:'UPI with /, - or spaces, or a new plot ID such as KBZ-0002.',staffHint:'NLA staff can also search by owner name.',notFound:'We couldn’t find “{q}”',checkUpi:'Check the UPI on your land title: it has five parts, e.g. 4/01/09/04/106.',sitesCovered:'Sites covered',needHelp:'Need help? Call NLA on [NLA hotline] or email',stillCant:'Still can’t find it? Call NLA on [NLA hotline] or email',formatHint:'Format: five parts separated by /, - or spaces, e.g. 4/01/09/04/106 or 4-01-09-04-106. New plot IDs look like KBZ-0002.',didYouMean:'Did you mean',noMatch:'No parcel or new plot with this number is in the sites covered so far.',nameBlocked:'Searching by owner name is only available to NLA staff. Please enter the UPI shown on your land title.',
myLand:'My land',allocProposed:'Allocation: Proposed',oldArea:'Old area',existingParcel:'Existing parcel',contributed:'Contributed',ofYourLand:'of your land',returned:'Area returned',outputArea:'Output area',whatLands:'What lands on my old parcel',whatLandsYour:'What lands on your old parcel',stNew:'New building plots',stRoad:'Road',stPub:'Public / green space',noPlotTitle:'No new building plot sits on this parcel',
noPlotBody:'In the proposed layout, all of this land becomes road or public space. Your land is still recorded in the project, with an output area of {out}. How this is allocated is decided at the plot reallocation stage, following the rules agreed with landholders. NLA will contact you before any allocation is final.',
noPlotPdf:'In the proposed layout, all of this parcel becomes road or public space. Your output area of {out} is allocated at the plot reallocation stage, following the rules agreed with landholders.',
talkTeam:'Talk to the NLA site team',plotsOnLand:'New plots on your land ({n})',subdividedNote:'Subdivided from your parcel; final allocation pending',plotWord:'plot',fromYou:'from you',ofPlot:'of plot',sharedWith1:'Shared with 1 other UPI',sharedWithN:'Shared with {n} other UPIs',onlyYours:'Only from your land',alsoFrom:'Also from:',dlPdf:'Download PDF',share:'Share link',report:'Report a problem',openDetails:'Open details',
lgSolid:'Solid = from your land',lgHatch:'Hatched = from neighbours’ land',lgRoad:'Road / public space on your parcel',lgOutline:'Your old parcel',lgPiece:'Coloured piece = land from each source UPI',lgSrc:'Source parcel outline',lgSel:'Selected plot',
encMort:'This parcel is mortgaged. NLA will contact you and your bank about the mortgage before the new plot is registered.',encRestr:'This parcel has a legal restriction. NLA will contact you about it before the new plot is registered.',encProv:'This parcel has a provisional title. NLA will contact you to confirm your rights before registration.',encPend:'A transaction is pending on this parcel. NLA will contact you about it before reallocation.',
locFmt:'{v} village · {c} cell · {s} sector',noAdmin:'Administrative units not recorded',luNone:'Land use not recorded',joint:'joint ownership',pdfPreview:'A4 preview · one page',print:'Print / Save as PDF',close:'Close',pdfTitle:'Land readjustment · My land',printed:'printed',pdfBefore:'Before · your parcel today',pdfAfter:'After · proposed layout on your parcel',pdfPlots:'New plots subdivided from your parcel',pdfFoot:'Subdivided from your parcel; final allocation pending. Geometric lineage based on {layout} and {src}.',copied:'Link copied. Owner names stay hidden for the public.',tbc:'Date to be confirmed',noGeom:'This parcel’s boundary is not mapped in the current extract. It will appear on the map after the updated survey.',enOnly:'Some sections are available in English only for now'};

const RW={story:'Inkuru',map:'Ikarita',analytics:'Isesengura',about:'Ibyerekeye',overview:'Incamake y’igihugu',find:'Shaka ubutaka bwawe',ph:'Andika UPI yawe, urugero 4/01/09/04/106',search:'Shakisha',signin:'Injira',dm:'Gucunga amakuru',
allSites:'ahantu hose',hint:'UPI ifite /, - cyangwa imyanya, cyangwa nomero y’ikibanza gishya nka KBZ-0002.',staffHint:'Abakozi ba NLA bashobora no gushakisha bakoresheje izina rya nyir’ubutaka.',notFound:'Ntitwabonye “{q}”',checkUpi:'Reba UPI iri ku cyangombwa cy’ubutaka bwawe: igizwe n’ibice bitanu, urugero 4/01/09/04/106.',sitesCovered:'Ahantu harimo',needHelp:'Ukeneye ubufasha? Hamagara NLA kuri [NLA hotline] cyangwa wandikire',stillCant:'Ntabwo urabibona? Hamagara NLA kuri [NLA hotline] cyangwa wandikire',formatHint:'Imiterere: ibice bitanu bitandukanyijwe na /, - cyangwa imyanya, urugero 4/01/09/04/106 cyangwa 4-01-09-04-106. Nomero z’ibibanza bishya ni nka KBZ-0002.',didYouMean:'Wenda washakaga',noMatch:'Nta butaka cyangwa ikibanza gishya gifite iyi nomero kiri mu hantu hamaze gushyirwamo.',nameBlocked:'Gushakisha ukoresheje izina rya nyir’ubutaka byemewe abakozi ba NLA gusa. Andika UPI iri ku cyangombwa cy’ubutaka bwawe.',
myLand:'Ubutaka bwanjye',allocProposed:'Igabanywa: Riteganyijwe',oldArea:'Ubuso bwa mbere',existingParcel:'Ubutaka buriho',contributed:'Umusanzu',ofYourLand:'by’ubutaka bwawe',returned:'Ubuso usubizwa',outputArea:'Ubuso busigaye',whatLands:'Ibizaba ku butaka bwanjye bwa mbere',whatLandsYour:'Ibizaba ku butaka bwawe bwa mbere',stNew:'Ibibanza bishya byo kubakamo',stRoad:'Umuhanda',stPub:'Ahantu rusange / h’icyatsi',noPlotTitle:'Nta kibanza gishya cyo kubakamo kiri kuri ubu butaka',
noPlotBody:'Mu gishushanyo giteganyijwe, ubu butaka bwose buzaba umuhanda cyangwa ahantu rusange. Ubutaka bwawe buracyanditse mu mushinga, bufite ubuso busigaye bwa {out}. Uko buzagabanywa bizemezwa mu cyiciro cyo kugabanya ibibanza, hakurikijwe amategeko yumvikanyweho n’abafite ubutaka. NLA izakuvugisha mbere y’uko igabanywa ryemezwa burundu.',
noPlotPdf:'Mu gishushanyo giteganyijwe, ubu butaka bwose buzaba umuhanda cyangwa ahantu rusange. Ubuso busigaye bwa {out} buzagabanywa mu cyiciro cyo kugabanya ibibanza, hakurikijwe amategeko yumvikanyweho.',
talkTeam:'Vugana n’itsinda rya NLA',plotsOnLand:'Ibibanza bishya ku butaka bwawe ({n})',subdividedNote:'Byakomotse ku butaka bwawe; igabanywa rya nyuma ntiriremezwa',plotWord:'ikibanza',fromYou:'bivuye kuri wowe',ofPlot:'by’ikibanza',sharedWith1:'Gisangiwe na UPI 1 yindi',sharedWithN:'Gisangiwe na UPI {n} zindi',onlyYours:'Kivuye ku butaka bwawe gusa',alsoFrom:'Kinavuye kuri:',dlPdf:'Kuramo PDF',share:'Sangiza umurongo',report:'Menyesha ikibazo',openDetails:'Reba birambuye',
lgSolid:'Ibara ryuzuye = bivuye ku butaka bwawe',lgHatch:'Imirongo = bivuye ku butaka bw’abaturanyi',lgRoad:'Umuhanda / ahantu rusange ku butaka bwawe',lgOutline:'Ubutaka bwawe bwa mbere',lgPiece:'Igice gifite ibara = ubutaka buvuye kuri buri UPI',lgSrc:'Imbibi z’ubutaka bw’inkomoko',lgSel:'Ikibanza cyatoranyijwe',
encMort:'Ubu butaka bufite ingwate. NLA izakuvugisha hamwe na banki yawe ku bijyanye n’ingwate mbere y’uko ikibanza gishya cyandikwa.',encRestr:'Ubu butaka bufite inzitizi y’amategeko. NLA izakuvugisha kuri yo mbere y’uko ikibanza gishya cyandikwa.',encProv:'Ubu butaka bufite icyangombwa cy’agateganyo. NLA izakuvugisha kugira ngo yemeze uburenganzira bwawe mbere yo kwandikisha.',encPend:'Hari igikorwa kitararangira kuri ubu butaka. NLA izakuvugisha kuri cyo mbere yo kugabanya ibibanza.',
locFmt:'Umudugudu: {v} · Akagari: {c} · Umurenge: {s}',noAdmin:'Inzego z’ubuyobozi ntizanditswe',luNone:'Imikoreshereze y’ubutaka ntiyanditswe',joint:'ubutaka bufatanyijwe',pdfPreview:'Igaragaza rya A4 · urupapuro rumwe',print:'Capa / Bika nka PDF',close:'Funga',pdfTitle:'Kuvugurura imiterere y’ubutaka · Ubutaka bwanjye',printed:'byacapwe',pdfBefore:'Mbere · ubutaka bwawe uyu munsi',pdfAfter:'Nyuma · igishushanyo giteganyijwe ku butaka bwawe',pdfPlots:'Ibibanza bishya byakomotse ku butaka bwawe',pdfFoot:'Byakomotse ku butaka bwawe; igabanywa rya nyuma ntiriremezwa. Isano ishingiye kuri {layout} na {src}.',copied:'Umurongo wakoporowe. Amazina ya ba nyir’ubutaka ntagaragara ku baturage.',tbc:'Itariki izemezwa',noGeom:'Imbibi z’ubu butaka ntiziri ku ikarita mu makuru ariho ubu. Zizagaragara ku ikarita nyuma y’ipima rishya.',enOnly:'Bimwe mu bice biraboneka mu Cyongereza gusa ubu'};

const FR={story:'Récit',map:'Carte',analytics:'Analyses',about:'À propos',overview:'Vue nationale',find:'Trouver ma parcelle',ph:'Saisissez votre UPI, ex. 4/01/09/04/106',search:'Rechercher',signin:'Se connecter',dm:'Gestion des données',
allSites:'tous les sites',hint:'UPI avec /, - ou espaces, ou identifiant de nouveau lot comme KBZ-0002.',staffHint:'Le personnel de la NLA peut aussi chercher par nom de propriétaire.',notFound:'Nous n’avons pas trouvé « {q} »',checkUpi:'Vérifiez l’UPI sur votre titre foncier : il comporte cinq parties, ex. 4/01/09/04/106.',sitesCovered:'Sites couverts',needHelp:'Besoin d’aide ? Appelez la NLA au [NLA hotline] ou écrivez à',stillCant:'Toujours introuvable ? Appelez la NLA au [NLA hotline] ou écrivez à',formatHint:'Format : cinq parties séparées par /, - ou des espaces, ex. 4/01/09/04/106 ou 4-01-09-04-106. Les nouveaux lots ressemblent à KBZ-0002.',didYouMean:'Vouliez-vous dire',noMatch:'Aucune parcelle ni nouveau lot avec ce numéro dans les sites couverts à ce jour.',nameBlocked:'La recherche par nom de propriétaire est réservée au personnel de la NLA. Saisissez l’UPI figurant sur votre titre foncier.',
myLand:'Ma parcelle',allocProposed:'Attribution : proposée',oldArea:'Surface initiale',existingParcel:'Parcelle existante',contributed:'Contribution',ofYourLand:'de votre terrain',returned:'Surface restituée',outputArea:'Surface de sortie',whatLands:'Ce qui occupe mon ancienne parcelle',whatLandsYour:'Ce qui occupe votre ancienne parcelle',stNew:'Nouveaux lots à bâtir',stRoad:'Route',stPub:'Espace public / vert',noPlotTitle:'Aucun nouveau lot à bâtir sur cette parcelle',
noPlotBody:'Dans le plan proposé, tout ce terrain devient route ou espace public. Votre terrain reste enregistré dans le projet, avec une surface de sortie de {out}. Son attribution est décidée lors de la réattribution des lots, selon les règles convenues avec les propriétaires. La NLA vous contactera avant toute attribution définitive.',
noPlotPdf:'Dans le plan proposé, toute cette parcelle devient route ou espace public. Votre surface de sortie de {out} est attribuée lors de la réattribution des lots, selon les règles convenues avec les propriétaires.',
talkTeam:'Contacter l’équipe NLA du site',plotsOnLand:'Nouveaux lots sur votre terrain ({n})',subdividedNote:'Issus de votre parcelle ; attribution finale en attente',plotWord:'lot',fromYou:'de votre terrain',ofPlot:'du lot',sharedWith1:'Partagé avec 1 autre UPI',sharedWithN:'Partagé avec {n} autres UPI',onlyYours:'Uniquement votre terrain',alsoFrom:'Provient aussi de :',dlPdf:'Télécharger le PDF',share:'Partager le lien',report:'Signaler un problème',openDetails:'Voir le détail',
lgSolid:'Plein = issu de votre terrain',lgHatch:'Hachuré = issu du terrain des voisins',lgRoad:'Route / espace public sur votre parcelle',lgOutline:'Votre ancienne parcelle',lgPiece:'Pièce colorée = terrain de chaque UPI source',lgSrc:'Contour de la parcelle source',lgSel:'Lot sélectionné',
encMort:'Cette parcelle est hypothéquée. La NLA vous contactera, vous et votre banque, au sujet de l’hypothèque avant l’enregistrement du nouveau lot.',encRestr:'Cette parcelle fait l’objet d’une restriction légale. La NLA vous contactera à ce sujet avant l’enregistrement du nouveau lot.',encProv:'Le titre de cette parcelle est provisoire. La NLA vous contactera pour confirmer vos droits avant l’enregistrement.',encPend:'Une transaction est en cours sur cette parcelle. La NLA vous contactera à ce sujet avant la réattribution.',
locFmt:'Village {v} · Cellule {c} · Secteur {s}',noAdmin:'Unités administratives non renseignées',luNone:'Usage du sol non renseigné',joint:'copropriété',pdfPreview:'Aperçu A4 · une page',print:'Imprimer / Enregistrer en PDF',close:'Fermer',pdfTitle:'Remembrement foncier · Ma parcelle',printed:'imprimé le',pdfBefore:'Avant · votre parcelle aujourd’hui',pdfAfter:'Après · plan proposé sur votre parcelle',pdfPlots:'Nouveaux lots issus de votre parcelle',pdfFoot:'Issus de votre parcelle ; attribution finale en attente. Filiation géométrique basée sur {layout} et {src}.',copied:'Lien copié. Les noms des propriétaires restent masqués pour le public.',tbc:'Date à confirmer',noGeom:'Les limites de cette parcelle ne sont pas cartographiées dans l’extrait actuel. Elles apparaîtront sur la carte après le nouveau levé.',enOnly:'Certaines sections ne sont disponibles qu’en anglais pour l’instant'};

const LU={RW:{Agricultural:'Ubuhinzi',Residential:'Guturamo','Commercial activities':'Ubucuruzi',Forestry:'Amashyamba','Public facility':'Ibikorwa rusange'},
  FR:{Agricultural:'Agricole',Residential:'Résidentiel','Commercial activities':'Activités commerciales',Forestry:'Forestier','Public facility':'Équipement public'}};
window.LR_I18N={T:{EN,RW,FR},LU};
})();
