/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateIndexRouteImport } from './routes/private/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PrivateNewRouteImport } from './routes/private/new'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as PrivateSlugEditRouteImport } from './routes/private/$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/private/',
  path: '/private/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateNewRoute = PrivateNewRouteImport.update({
  id: '/private/new',
  path: '/private/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSlugEditRoute = PrivateSlugEditRouteImport.update({
  id: '/private/$slug/edit',
  path: '/private/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/private/new': typeof PrivateNewRoute
  '/admin/': typeof AdminIndexRoute
  '/private/': typeof PrivateIndexRoute
  '/private/$slug/edit': typeof PrivateSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/private/new': typeof PrivateNewRoute
  '/admin': typeof AdminIndexRoute
  '/private': typeof PrivateIndexRoute
  '/private/$slug/edit': typeof PrivateSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/private/new': typeof PrivateNewRoute
  '/admin/': typeof AdminIndexRoute
  '/private/': typeof PrivateIndexRoute
  '/private/$slug/edit': typeof PrivateSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/$slug'
    | '/private/new'
    | '/admin/'
    | '/private/'
    | '/private/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$slug'
    | '/private/new'
    | '/admin'
    | '/private'
    | '/private/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/docs/$slug'
    | '/private/new'
    | '/admin/'
    | '/private/'
    | '/private/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSlugRoute: typeof DocsSlugRoute
  PrivateNewRoute: typeof PrivateNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateSlugEditRoute: typeof PrivateSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/': {
      id: '/private/'
      path: '/private'
      fullPath: '/private/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/new': {
      id: '/private/new'
      path: '/private/new'
      fullPath: '/private/new'
      preLoaderRoute: typeof PrivateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/$slug/edit': {
      id: '/private/$slug/edit'
      path: '/private/$slug/edit'
      fullPath: '/private/$slug/edit'
      preLoaderRoute: typeof PrivateSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSlugRoute: DocsSlugRoute,
  PrivateNewRoute: PrivateNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateSlugEditRoute: PrivateSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
